
# GPU SETTING
GPU1: 1 #3
GPU2: 1 #1
DATA_PARALLEL: False

# DATA OPTIONS
INPUT_DIM: 3
DATASET: CelebA
IMG_SIZE: 128
CELEBA_CROP_SIZE: 178
CELEBA_PATH: data/CelebA_nocrop/images
ATTR_PATH: data/list_attr_celeba.txt
C_DIM: 4
SELECTED_ATTRS: [Black_Hair, Blond_Hair, Brown_Hair, Smiling]
# Mustache, No_Beard, Male, Goatee

NUM_ITERS: 200000
BATCH_SIZE: 8
G_LR: 0.0001
D_LR: 0.0001
BETA1: 0.5
BETA2: 0.999
GAMMA: 0.5
WEIGHT_DECAY: 0.0001
LR_POLICY: step

NUM_ITERS_DECAY: 100000
STEP_SIZE: 10000

N_CRITIC: 5
INIT: kaiming
LAMBDA_X_REC: 10.0
LAMBDA_X_CYC: 10.0
LAMBDA_LATENT_REC: 1.0
LAMBDA_S_B: 1.0
LAMBDA_S_F: 1.0
LAMBDA_CLS: 1.0
LAMBDA_GP: 10.0

LAMBDA_MASK_MIN: 0.0001
LAMBDA_MASK_SMOOTH: 0.0
LAMBDA_MASK_SIM: 1.0
LAMBDA_STYLE_REG: 0.01

# MODEL OPTIONS
G:
  FIRST_DIM: 64
  MLP_DIM: 256
  STYLE_DIM: 8
  N_RES_BLOCKS: 8

D:
  FIRST_DIM: 64 
  N_RES_BLOCKS: 6


# ETC
START: 0
LOAD_MODEL: False
NUM_WORKERS: 1
MODE: train
PRINT_EVERY: 1000
NUM_PRINT: 2 # min: 1
MODEL_SAVE_PATH: models/
SAVE_NAME: min_0.0001_sim1.0_reg0.01_color_hair